version: "3"
services: 
  db:
    image: postgres:alpine
    container_name: cashbackgb-db
    ports: 
      - "5432:5432"
    env_file: 
      - .env
    volumes:
      - ".data/postgres:/var/lib/postgresql/data"

  api:
    build: .
    container_name: cashbackgb-api
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - "db"
    command: > 
      sh -c "sleep 10 
      && alembic upgrade head 
      && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"