"""First commit

Revision ID: 11558fbe6d88
Revises: 
Create Date: 2022-01-21 22:07:27.086830

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "11558fbe6d88"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
