"""remove description index from purchase status

Revision ID: a21f59d1e97e
Revises: 0b3e71986e87
Create Date: 2022-01-22 11:28:43.901362

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "a21f59d1e97e"
down_revision = "0b3e71986e87"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_purchase_status_description", table_name="purchase_status"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_purchase_status_description",
        "purchase_status",
        ["description"],
        unique=False,
    )
    # ### end Alembic commands ###
