"""add cashback value column in purchase table

Revision ID: dc28cb1867e6
Revises: a21f59d1e97e
Create Date: 2022-01-22 12:00:27.682635

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "dc28cb1867e6"
down_revision = "a21f59d1e97e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "purchase", sa.Column("cashback_value", sa.Numeric(), nullable=False)
    )
    op.drop_index("ix_purchase_value", table_name="purchase")
    op.create_index(
        op.f("ix_purchase_value"), "purchase", ["value"], unique=False
    )
    op.create_index(
        op.f("ix_purchase_cashback_value"),
        "purchase",
        ["cashback_value"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_purchase_cashback_value"), table_name="purchase")
    op.drop_index(op.f("ix_purchase_value"), table_name="purchase")
    op.create_index("ix_purchase_value", "purchase", ["value"], unique=False)
    op.drop_column("purchase", "cashback_value")
    # ### end Alembic commands ###
